"""RBAC catalog mirrored from the hstaff backend (app/core/default_permissions.py).

This is our local replica of hstaff's roles + permissions, kept in sync manually
until C-level API credentials are available to pull them live from
GET /api/v1/admin/roles and /api/v1/admin/permissions.

Onboarded local users are granted hstaff's `school` tier (the entry rung of the
talent journey: school → soft-landing → foundation → growth). These tiers are
collectively treated as "learners" (see identity.enums.LEARNER_ROLES).
"""

# (codename, resource, action, description)
PERMISSIONS = [
    ("users:read", "users", "read", "View user list"),
    ("users:create", "users", "create", "Create new users"),
    ("users:update", "users", "update", "Edit user details"),
    (
        "users:manage",
        "users",
        "manage",
        "Edit privileged user fields (email, role, day-off)",
    ),
    ("users:promote", "users", "promote", "Promote a user one role level up"),
    ("users:demote", "users", "demote", "Demote a user one role level down"),
    (
        "users:resend_verification",
        "users",
        "resend_verification",
        "Resend verification email",
    ),
    ("departments:read", "departments", "read", "View departments"),
    ("departments:create", "departments", "create", "Create departments"),
    ("departments:update", "departments", "update", "Update departments"),
    ("departments:delete", "departments", "delete", "Delete departments"),
    ("departments:add_member", "departments", "add_member", "Add member to department"),
    (
        "departments:remove_member",
        "departments",
        "remove_member",
        "Remove member from department",
    ),
    ("organizations:read", "organizations", "read", "View organizations"),
    ("organizations:update", "organizations", "update", "Update organizations"),
    ("projects:read", "projects", "read", "View projects"),
    ("projects:update", "projects", "update", "Update projects"),
    (
        "projects:pm_assign",
        "projects",
        "pm_assign",
        "Assign Project Manager to a project",
    ),
    ("hubstaff:sync_projects", "hubstaff", "sync_projects", "Sync Hubstaff projects"),
    (
        "hubstaff:sync_members",
        "hubstaff",
        "sync_members",
        "Sync Hubstaff project members",
    ),
    (
        "hubstaff:sync_activities",
        "hubstaff",
        "sync_activities",
        "Sync Hubstaff user activities",
    ),
    ("mentorship:read", "mentorship", "read", "View all mentorships"),
    ("mentorship:assign", "mentorship", "assign", "Assign mentor"),
    ("mentorship:reassign", "mentorship", "reassign", "Reassign mentor"),
    ("mentorship:delete", "mentorship", "delete", "Delete mentorship"),
    ("reports:view_projects", "reports", "view_projects", "View project-talent report"),
    ("reports:view_cycle", "reports", "view_cycle", "View cycle performance report"),
    (
        "reports:view_project_costs",
        "reports",
        "view_project_costs",
        "View project costs report",
    ),
    ("talents:all_view", "talents", "all_view", "View all talents list"),
    ("day_off:read", "day_off", "read", "View all day-off requests"),
    ("day_off:approve", "day_off", "approve", "Approve/reject day-off requests"),
    ("day_off:grant", "day_off", "grant", "Grant time-off to users"),
    ("day_off:delete", "day_off", "delete", "Delete day-off requests"),
    (
        "cycle_reflection:read",
        "cycle_reflection",
        "read",
        "View all cycle reflection forms",
    ),
    (
        "cycle_reflection:manage",
        "cycle_reflection",
        "manage",
        "Approve/reject cycle reflection forms",
    ),
    (
        "system_settings:deepwork",
        "system_settings",
        "deepwork",
        "Manage deepwork settings",
    ),
    (
        "system_settings:pnp",
        "system_settings",
        "pnp",
        "Manage progress planning settings",
    ),
    (
        "system_settings:discord",
        "system_settings",
        "discord",
        "Manage Discord integration settings",
    ),
    (
        "system_settings:scheduler",
        "system_settings",
        "scheduler",
        "Manage scheduler settings",
    ),
    (
        "system_settings:work_hours",
        "system_settings",
        "work_hours",
        "Manage work hours settings",
    ),
    ("system_settings:docs", "system_settings", "docs", "Manage API docs access"),
    (
        "system_settings:user_settings",
        "system_settings",
        "user_settings",
        "Manage per-user setting overrides",
    ),
    ("announcements:create", "announcements", "create", "Create new announcements"),
    ("announcements:update", "announcements", "update", "Edit any announcement"),
    ("announcements:delete", "announcements", "delete", "Delete any announcement"),
    (
        "work_schedule_slot_types:manage",
        "work_schedule_slot_types",
        "manage",
        "Manage work schedule slot types",
    ),
    ("score_metrics:create", "score_metrics", "create", "Create new score metrics"),
    ("score_metrics:update", "score_metrics", "update", "Update score metrics"),
    ("user_rates:read", "user_rates", "read", "View user hourly rates"),
    ("user_rates:create", "user_rates", "create", "Create user hourly rates"),
    ("user_rates:update", "user_rates", "update", "Update user hourly rates"),
    ("user_rates:delete", "user_rates", "delete", "Delete user hourly rates"),
    ("permissions:manage", "permissions", "manage", "Manage roles and permissions"),
    ("evaluation_forms:read", "evaluation_forms", "read", "View evaluation form data"),
    (
        "evaluation_forms:manage",
        "evaluation_forms",
        "manage",
        "Manage evaluation form data",
    ),
    (
        "rise:reports_read",
        "rise",
        "reports_read",
        "View monthly RISE evaluation reports",
    ),
]

# Shared C-suite / management permission bundle used by several roles.
_FULL_MANAGEMENT = [
    "talents:all_view",
    "users:read",
    "users:create",
    "users:update",
    "users:manage",
    "users:promote",
    "users:demote",
    "users:resend_verification",
    "departments:read",
    "departments:create",
    "departments:update",
    "departments:delete",
    "departments:add_member",
    "departments:remove_member",
    "organizations:read",
    "organizations:update",
    "projects:read",
    "projects:update",
    "projects:pm_assign",
    "hubstaff:sync_projects",
    "hubstaff:sync_members",
    "mentorship:read",
    "mentorship:assign",
    "mentorship:reassign",
    "mentorship:delete",
    "reports:view_projects",
    "day_off:approve",
    "day_off:grant",
    "day_off:delete",
    "user_rates:read",
    "user_rates:create",
    "user_rates:update",
    "user_rates:delete",
    "evaluation_forms:read",
    "evaluation_forms:manage",
    "rise:reports_read",
]

# name -> config. `is_system` marks roles that came from hstaff (cannot be deleted).
# Hierarchy (0 = highest):
#   superadmin > c-level > advisor > academy-manager > …
# C-level is the single C-suite role covering CEO, CTO, COO, CFO, CMO and all
# chief officer seats. Membership is assigned by the superadmin or a sitting C-level.
ROLES = {
    "superadmin": {
        "display_name": "Superadmin",
        "description": "Full system access — bypasses all permission checks",
        "level": 0,
        "is_system": True,
        "permissions": [],
    },
    "c-level": {
        "display_name": "C-Level",
        "description": "C-suite executive — for CEOs, CTOs, COOs, CFOs, CMOs and all chief officer roles — full management access",
        "level": 1,
        "is_system": True,
        "permissions": list(_FULL_MANAGEMENT),
    },
    "advisor": {
        "display_name": "Advisor",
        "description": "High-level advisory role",
        "level": 2,
        "is_system": True,
        "permissions": ["talents:all_view"],
    },
    "academy-manager": {
        "display_name": "Academy Manager",
        "description": "Owns the onboarding process — runs interviews, decides payments and access",
        "level": 3,
        "is_system": False,
        "permissions": ["talents:all_view", "users:read", "users:create"],
    },
    "examiner": {
        "display_name": "Examiner",
        "description": "Local role — administers Academy problems, Data Lab and exams",
        "level": 3,
        "is_system": False,
        "permissions": [],
    },
    "department-head": {
        "display_name": "Department Head",
        "description": "Department management — mentorship and department access",
        "level": 4,
        "is_system": True,
        "permissions": [
            "talents:all_view",
            "mentorship:read",
            "mentorship:assign",
            "mentorship:reassign",
            "mentorship:delete",
        ],
    },
    "hr": {
        "display_name": "HR",
        "description": "Human resources — mentorship and people management",
        "level": 5,
        "is_system": True,
        "permissions": [
            "talents:all_view",
            "users:read",
            "users:create",
            "mentorship:read",
            "mentorship:assign",
            "mentorship:reassign",
            "mentorship:delete",
            "reports:view_projects",
            "reports:view_cycle",
            "cycle_reflection:manage",
            "day_off:approve",
            "day_off:grant",
            "day_off:delete",
            "work_schedule_slot_types:manage",
            "score_metrics:create",
            "score_metrics:update",
            "evaluation_forms:read",
            "evaluation_forms:manage",
            "rise:reports_read",
        ],
    },
    "pm": {
        "display_name": "PM",
        "description": "Project management",
        "level": 6,
        "is_system": True,
        "permissions": ["talents:all_view", "evaluation_forms:read"],
    },
    "mentor": {
        "display_name": "Mentor",
        "description": "Can mentor talents",
        "level": 7,
        "is_system": True,
        "permissions": ["talents:all_view", "evaluation_forms:read"],
    },
    "talent": {
        "display_name": "Talent",
        "description": "Regular employee",
        "level": 8,
        "is_system": True,
        "permissions": ["talents:all_view", "evaluation_forms:read"],
    },
    "foundation": {
        "display_name": "Foundation",
        "description": "Foundation program",
        "level": 9,
        "is_system": True,
        "permissions": ["talents:all_view", "evaluation_forms:read"],
    },
    "softlanding": {
        "display_name": "Softlanding",
        "description": "Softlanding program",
        "level": 10,
        "is_system": True,
        "permissions": ["talents:all_view", "evaluation_forms:read"],
    },
    "school": {
        "display_name": "School",
        "description": "School program",
        "level": 11,
        "is_system": True,
        "permissions": ["talents:all_view"],
    },
}
